export const ADD_USER = 'ADD_USER'
export const FETCH_USERS = 'FETCH_USERS'
export const ADD_MESSAGE = 'ADD_MESSAGE'
export const FETCH_MESSAGES = 'FETCH_MESSAGES'
export const ADD_GROUP = 'ADD_GROUP'
export const FETCH_GROUPS = 'FETCH_GROUPS'
export const CLEAR_GROUPS = 'CLEAR_GROUPS'
